const languages = {
  eng: {
    "for-business": "for business",
    "download-app": "download app",
    h1: "Stay connected, wherever you are",
    p1: "Vorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "find-my-powerbank": "Find My Power Bank",
    "phase-1": "on the bus station",
    "phase-2": "in the shop",
    "phase-3": "in the SPA",
    "phase-4": "in the shopping mall",
    "phase-5": "at the airport",
    "phase-6": "on the beach",
    "phase-7": "at the park",
    "phase-8": "in the office",
    "phase-9": "in the coffee shop",
    "phase-10": "on the train",
    "phase-11": "in the library",
    "phase-12": "at the gym",
    "phase-13": "in the movie theater",
    "phase-14": "at the restaurant",
    "phase-15": "in the museum",
    "phase-16": "at the concert hall",
    "phase-17": "on the mountain top",
    "phase-18": "at the festival",
    "phase-19": "at the hotel lobby",
    "phase-20": "on a boat",
    "get-the-app__span": "Get the app",
    "get-the-app__h2": "Get the App and Never Run Out of Battery",
    "get-the-app__p2":
      "Download the app now to easily locate nearby power banks and keep your devices charged wherever you are!",
    "how-it-works": "How It Works",
    hiw__h3_1: "Download the app",
    hiw__p2_1: "Install our app on your device.",
    hiw__h3_2: "Find and scan",
    hiw__p2_1:
      "Use the map in the app to locate a nearby power bank and scan the QR code.",
    hiw__h3_3: "Rent the power bank",
    hiw__p2_3: "Select the power bank you need and rent it via the app.",
    hiw__h3_4: "Use and return",
    hiw__p2_4:
      "Use the power bank and return it to the nearest station when you're done.",
    hiw__span: "Affordable Rental Plans",
    hiw__h2: "Simple Pricing, No Hidden Fees",
    price__h3_1: "First Hour",
    "price__price-itself_1": "Free",
    price__subtext_1: "*Free for new users after registration",
    price__h3_2: "After 1 Hour",
    "per-hour": "/per hour",
    popular: "popular",
    price__h3_3: "Full Day",
    "per-day": "/per day",
    wmud__span: "What Makes Us Different",
    wmud__h3_1: "Convenient Locations",
    wmud__p2_1:
      "Find power banks at stations conveniently located throughout the city.",
    wmud__h3_2: "User-Friendly App",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps.",
    wmud__h3_3: "High-Quality Devices",
    wmud__p2_3:
      "Our power banks are reliable, fast-charging, and compatible with most devices",
    wmud__h3_4: "Affordable Pricing",
    wmud__p2_4:
      "Enjoy flexible rental plans that fit your needs, with no hidden fees.",
    map__span: "Map of Stations",
    map__h2: "Find the Nearest Charging Station",
    map__p2:
      "Easily find all nearby power bank stations and stay powered up wherever you are!",
    map__btn: "Find Stations Near Me",
    "download-app__h2": "Battery boost at the cost of a bottle of water",
    "download-app__p2":
      "Quick, easy, and budget-friendly – download the app to stay connected",
    "slider__h3-1": "Secure Payments",
    "slider__p-1": "Make quick and safe payments directly through the app.",
    "slider__h3-2": "User-Friendly Interface",
    "slider__p-2":
      "Easily rent, track, and return power banks with a simple app design.",
    "slider__h3-3": "Real-Time Tracking",
    "slider__p-3":
      "Know exactly where to find a station at any moment with our live map.",
    "slider__h3-4": "Exclusive Deals",
    "slider__p-4": "Enjoy discounts and perks available only for app users.",
    "slider__h3-5": "Sustainable Solution",
    "slider__p-5":
      " Choose eco-friendly reusable power banks to help reduce waste.",
    form__span: "Get in Touch",
    form__h2: "Looking to Partner or Need Support?",
    form__p2:
      "Need help, have feedback, or want to partner with us? Fill out the form below, and we’ll get back to you soon",
    checkbox__p:
      "By submitting this form, you consent to the processing of your personal data.",
    form__send: "send",
    placeholder__name: "*your name",
    placeholder__email_or_phone: "*e-mail or phone number",
    placeholder__name: "*your name",
    placeholder__email_or_phone: "*e-mail or phone number",
    error__name_required: "Name is required.",
    error__name_length: "Name must be between 2 and 20 characters.",
    error__name_letters: "Name must only contain letters.",
    error__email_phone_required: "Email or phone number is required.",
    error__phone_format:
      "Phone number must be 10-15 digits, with or without '+' sign.",
    error__email_format: "Please enter a valid email address.",
    form__success_h2: "Thank you for your submission!",
    form__success_p2:
      "We’ll be in touch shortly to discuss the next steps. Looking forward to working with you!",
    form__success_btn: "Ok",
    business__main_h1: "Partner with Us to Power Up Your Business",
    business__main_p1: "Boost your reach and keep customers connected",
    business__main_btn: "Get Started",
    counts__h2: "Make Money by Offering a Smarter Service",
    counts__h3_1: "700+",
    counts__p2_1: "businesses already partner with us.",
    counts__h3_2: "99%",
    counts__p2_2: "customer satisfaction rate with our service.",
    counts__h3_3: "24/7",
    counts__p2_3: "support to ensure seamless operations.",
    counts__h3_4: "1M+",
    counts__p2_4: "devices charged globally.",
    places__span: "Ideal Business Locations",
    places__h2: "Perfect FOR High-Traffic Businesses",
    places__p2:
      "Provide a convenient charging solution that enhances your customers’  experience while generating extra income for your business.",
    places__h3_1: "Shopping Mall",
    places__h3_2: "Convenience Store",
    places__h3_3: "Airport",
    places__h3_4: "Spa",
    places__h3_5: "Gym",
    places__h3_6: "Co-Working Space",
    places__h3_7: "Event Venue",
    places__h3_8: "Library",
    places__h3_9: "Restaurant",
    places__h3_10: "Hotel",
    places__h3_11: "Beauty Salon",
    places__h3_12: "Clinic",
    faq__span: "FAQ: Partnering with Us",
    faq__h2: "Common Questions About Collaboration",
    faq__h3_1: "How can my business benefit from hosting a charging station?",
    faq__answer_1:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    faq__h3_2: "What does it cost to install a charging station?",
    faq__answer_2:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    faq__h3_3: "What kind of support do you offer to business partners?",
    faq__answer_3:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    faq__h3_4: "How much space does the charging station require?",
    faq__answer_4:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    faq__h3_5:
      "What types of businesses are ideal for hosting a charging station?",
    faq__answer_5:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    faq__h3_6: "How do I get started with a partnership?",
    faq__answer_6:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores!",
    become_a_partner: "Become a partner",
    find_the_nearest_station: "Find the nearest station",
    pricing_policy: "Pricing policy",
    faq: "FAQ",
    all_rights_reserved: "All rights reserved",
    policy: "Policy",
    terms_of_use: "Terms of use",
  },
  pl: {
    "for-business": "dla biznesu",
    "download-app": "pobierz aplikację",
    h1: "Stay connected, wherever you are PL",
    p1: "Vorem ipsum dolor sit amet, consectetur adipiscing elit. PL",
    "find-my-powerbank": "Find My Power Bank PL",
    "phase-1": "na stacji autobusowej",
    "phase-2": "w sklepie",
    "phase-3": "w SPA",
    "phase-4": "w centrum handlowym",
    "phase-5": "na lotnisku",
    "phase-6": "na plaży",
    "phase-7": "w parku",
    "phase-8": "w biurze",
    "phase-9": "w kawiarni",
    "phase-10": "w pociągu",
    "phase-11": "w bibliotece",
    "phase-12": "na siłowni",
    "phase-13": "w kinie",
    "phase-14": "w restauracji",
    "phase-15": "w muzeum",
    "phase-16": "w sali koncertowej",
    "phase-17": "na szczycie góry",
    "phase-18": "na festiwalu",
    "phase-19": "w hotelu",
    "phase-20": "na łodzi",
    "get-the-app__span": "Get the app PL",
    "get-the-app__h2": "Get the App and Never Run Out of Battery PL",
    "get-the-app__p2":
      "Download the app now to easily locate nearby power banks and keep your devices charged wherever you are! PL",
    "how-it-works": "How It Works PL",
    hiw__h3_1: "Download the app PL",
    hiw__p2_1: "Install our app on your device. PL",
    hiw__h3_2: "Find and scan PL",
    hiw__p2_1:
      "Use the map in the app to locate a nearby power bank and scan the QR code. PL",
    hiw__h3_3: "Rent the power bank PL",
    hiw__p2_3: "Select the power bank you need and rent it via the app. PL",
    hiw__h3_4: "Use and return PL",
    hiw__p2_4:
      "Use the power bank and return it to the nearest station when you're done. PL",
    hiw__span: "Affordable Rental Plans PL",
    hiw__h2: "Simple Pricing, No Hidden Fees PL",
    price__h3_1: "First Hour PL",
    "price__price-itself_1": "Free PL",
    price__subtext_1: "*Free for new users after registration PL",
    price__h3_2: "After 1 Hour PL",
    "per-hour": "/per hour PL",
    popular: "popular PL",
    price__h3_3: "Full Day PL",
    "per-day": "/per day PL",
    wmud__span: "What Makes Us Different PL",
    wmud__h3_1: "Convenient Locations PL",
    wmud__p2_1:
      "Find power banks at stations conveniently located throughout the city. PL",
    wmud__h3_2: "User-Friendly App PL",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps. PL",
    wmud__h3_3: "High-Quality Devices PL",
    wmud__p2_3:
      "Our power banks are reliable, fast-charging, and compatible with most devices PL",
    wmud__h3_4: "Affordable Pricing PL",
    wmud__p2_4:
      "Enjoy flexible rental plans that fit your needs, with no hidden fees. PL",
    map__span: "Map of Stations PL",
    map__h2: "Find the Nearest Charging Station PL",
    map__p2:
      "Easily find all nearby power bank stations and stay powered up wherever you are! PL",
    map__btn: "Find Stations Near Me PL",
    "download-app__h2": "Battery boost at the cost of a bottle of water PL",
    "download-app__p2":
      "Quick, easy, and budget-friendly – download the app to stay connected PL",
    "slider__h3-1": "Secure Payments PL",
    "slider__p-1": "Make quick and safe payments directly through the app. PL",
    "slider__h3-2": "User-Friendly Interface PL",
    "slider__p-2":
      "Easily rent, track, and return power banks with a simple app design. PL",
    "slider__h3-3": "Real-Time Tracking PL",
    "slider__p-3":
      "Know exactly where to find a station at any moment with our live map. PL",
    "slider__h3-4": "Exclusive Deals PL",
    "slider__p-4": "Enjoy discounts and perks available only for app users. PL",
    "slider__h3-5": "Sustainable Solution PL",
    "slider__p-5":
      " Choose eco-friendly reusable power banks to help reduce waste. PL",
    form__h2: "Looking to Partner or Need Support? PL",
    form__p2:
      "Need help, have feedback, or want to partner with us? Fill out the form below, and we’ll get back to you soon PL",
    checkbox__p:
      "By submitting this form, you consent to the processing of your personal data. PL",
    form__send: "send PL",
    placeholder__name: "*your name PL",
    placeholder__email_or_phone: "*e-mail or phone number PL",
    placeholder__name: "*Twoje imię PL",
    placeholder__email_or_phone: "*e-mail lub numer telefonu PL",
    error__name_required: "Imię jest wymagane. PL",
    error__name_length: "Imię musi mieć od 2 do 20 znaków. PL",
    error__name_letters: "Imię może zawierać tylko litery. PL",
    error__email_phone_required: "E-mail lub numer telefonu jest wymagany. PL",
    error__phone_format:
      "Numer telefonu musi mieć od 10 do 15 cyfr, z lub bez znaku '+'. PL",
    error__email_format: "Proszę podać poprawny adres e-mail. PL",
    form__success_h2: "Thank you for your submission! PL",
    form__success_p2:
      "We’ll be in touch shortly to discuss the next steps. Looking forward to working with you! PL",
    form__success_btn: "Ok PL",
    business__main_h1: "Partner with Us to Power Up Your Business PL",
    business__main_p1: "Boost your reach and keep customers connected PL",
    business__main_btn: "Get Started PL",
    counts__h2: "Make Money by Offering a Smarter Service PL",
    counts__h3_1: "700+ PL",
    counts__p2_1: "businesses already partner with us. PL",
    counts__h3_2: "99% PL",
    counts__p2_2: "customer satisfaction rate with our service. PL",
    counts__h3_3: "24/7 PL",
    counts__p2_3: "support to ensure seamless operations. PL",
    counts__h3_4: "1M+ PL",
    counts__p2_4: "devices charged globally. PL",
    places__span: "Ideal Business Locations PL",
    places__h2: "Perfect FOR High-Traffic Businesses PL",
    places__p2:
      "Provide a convenient charging solution that enhances your customers’  experience while generating extra income for your business. PL",
    places__h3_1: "Shopping Mall PL",
    places__h3_2: "Convenience Store PL",
    places__h3_3: "Airport PL",
    places__h3_4: "Spa PL",
    places__h3_5: "Gym PL",
    places__h3_6: "Co-Working Space PL",
    places__h3_7: "Event Venue PL",
    places__h3_8: "Library PL",
    places__h3_9: "Restaurant PL",
    places__h3_10: "Hotel PL",
    places__h3_11: "Beauty Salon PL",
    places__h3_12: "Clinic PL",
    faq__span: "FAQ: Partnering with Us PL",
    faq__h2: "Common Questions About Collaboration PL",
    faq__h3_1:
      "How can my business benefit from hosting a charging station? PL",
    faq__answer_1:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    faq__h3_2: "What does it cost to install a charging station? PL",
    faq__answer_2:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    faq__h3_3: "What kind of support do you offer to business partners? PL",
    faq__answer_3:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    faq__h3_4: "How much space does the charging station require? PL",
    faq__answer_4:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    faq__h3_5:
      "What types of businesses are ideal for hosting a charging station? PL",
    faq__answer_5:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    faq__h3_6: "How do I get started with a partnership? PL",
    faq__answer_6:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci, asperiores! PL",
    become_a_partner: "Become a partner PL",
    find_the_nearest_station: "Find the nearest station PL",
    pricing_policy: "Pricing policy PL",
    faq: "FAQ PL",
    all_rights_reserved: "All rights reserved PL",
    policy: "Policy PL",
    terms_of_use: "Terms of use PL",
  },
};
