const languages = {
  eng: {
    "for-business": "for business",
    "download-app": "download app",
    h1: "Stay connected, wherever you are",
    p1: "Reliable energy for your journey!",
    "find-my-powerbank": "Find My Power Bank",
    "phase-1": "on the bus station",
    "phase-2": "in the shop",
    "phase-3": "in the SPA",
    "phase-4": "in the shopping mall",
    "phase-5": "at the airport",
    "phase-6": "on the beach",
    "phase-7": "at the park",
    "phase-8": "in the office",
    "phase-9": "in the coffee shop",
    "phase-10": "on the train",
    "phase-11": "in the library",
    "phase-12": "at the gym",
    "phase-13": "in the movie theater",
    "phase-14": "at the restaurant",
    "phase-15": "in the museum",
    "phase-16": "at the concert hall",
    "phase-17": "on the mountain top",
    "phase-18": "at the festival",
    "phase-19": "at the hotel lobby",
    "phase-20": "on a boat",
    "get-the-app__span": "Get the app",
    "get-the-app__h2": "Get the App and Never Run Out of Battery",
    "get-the-app__p2":
      "Download the app now to easily locate nearby power banks and keep your devices charged wherever you are!",
    "how-it-works": "How It Works",
    hiw__h3_1: "Download the app",
    hiw__p2_1: "Install our app on your device.",
    hiw__h3_2: "Find and scan",
    hiw__p2_1:
      "Use the map in the app to locate a nearby power bank and scan the QR code.",
    hiw__h3_3: "Rent the power bank",
    hiw__p2_3: "Select the power bank you need and rent it via the app.",
    hiw__h3_4: "Use and return",
    hiw__p2_4:
      "Use the power bank and return it to the nearest station when you're done.",
    hiw__span: "Affordable Rental Plans",
    hiw__h2: "Simple Pricing, No Hidden Fees",
    price__h3_1: "The first 15 minutes",
    "price__price-itself_1": "Free",
    price__subtext_1: "*Free for new users after registration",
    price__h3_2: "After 1 Hour",
    "per-hour": "/per hour",
    popular: "popular",
    price__h3_3: "Full Day",
    "per-day": "/per day",
    wmud__span: "What Makes Us Different",
    wmud__h3_1: "Convenient Locations",
    wmud__p2_1:
      "Find power banks at stations conveniently located throughout the city.",
    wmud__h3_2: "User-Friendly App",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps.",
    wmud__h3_3: "High-Quality Devices",
    wmud__p2_3:
      "Our power banks are reliable, fast-charging, and compatible with most devices",
    wmud__h3_4: "Affordable Pricing",
    wmud__p2_4:
      "Enjoy flexible rental plans that fit your needs, with no hidden fees.",
    map__span: "Map of Stations",
    map__h2: "Find the Nearest Charging Station",
    map__p2:
      "Easily find all nearby power bank stations and stay powered up wherever you are!",
    map__btn: "Find Stations Near Me",
    "download-app__h2": "Battery boost at the cost of a bottle of water",
    "download-app__p2":
      "Quick, easy, and budget-friendly – download the app to stay connected",
    "slider__h3-1": "Secure Payments",
    "slider__p-1": "Make quick and safe payments directly through the app.",
    "slider__h3-2": "User-Friendly Interface",
    "slider__p-2":
      "Easily rent, track, and return power banks with a simple app design.",
    "slider__h3-3": "Real-Time Tracking",
    "slider__p-3":
      "Know exactly where to find a station at any moment with our live map.",
    "slider__h3-4": "Exclusive Deals",
    "slider__p-4": "Enjoy discounts and perks available only for app users.",
    "slider__h3-5": "Sustainable Solution",
    "slider__p-5":
      " Choose eco-friendly reusable power banks to help reduce waste.",
    form__span: "Get in Touch",
    form__h2: "Looking to Partner or Need Support?",
    form__p2:
      "Need help, have feedback, or want to partner with us? Fill out the form below, and we’ll get back to you soon",
    checkbox__p:
      "By submitting this form, you consent to the processing of your personal data.",
    form__send: "send",
    placeholder__name: "*your name",
    placeholder__email_or_phone: "*e-mail or phone number",
    placeholder__name: "*your name",
    placeholder__email_or_phone: "*e-mail or phone number",
    error__name_required: "Name is required.",
    error__name_length: "Name must be between 2 and 20 characters.",
    error__name_letters: "Name must only contain letters.",
    error__email_phone_required: "Email or phone number is required.",
    error__phone_format:
      "Phone number must be 10-15 digits, with or without '+' sign.",
    error__email_format: "Please enter a valid email address.",
    form__success_h2: "Thank you for your submission!",
    form__success_p2:
      "We’ll be in touch shortly to discuss the next steps. Looking forward to working with you!",
    form__success_btn: "Ok",
    business__main_h1: "Partner with Us to Power Up Your Business",
    business__main_p1: "Boost your reach and keep customers connected",
    business__main_btn: "Get Started",
    counts__h2: "Make Money by Offering a Smarter Service",
    counts__h3_1: "700+",
    counts__p2_1: "businesses already partner with us.",
    counts__h3_2: "99%",
    counts__p2_2: "customer satisfaction rate with our service.",
    counts__h3_3: "24/7",
    counts__p2_3: "support to ensure seamless operations.",
    counts__h3_4: "1M+",
    counts__p2_4: "devices charged globally.",
    places__span: "Ideal Business Locations",
    places__h2: "Perfect FOR High-Traffic Businesses",
    places__p2:
      "Provide a convenient charging solution that enhances your customers’  experience while generating extra income for your business.",
    places__h3_1: "Shopping Mall",
    places__h3_2: "Convenience Store",
    places__h3_3: "Airport",
    places__h3_4: "Spa",
    places__h3_5: "Gym",
    places__h3_6: "Co-Working Space",
    places__h3_7: "Event Venue",
    places__h3_8: "Library",
    places__h3_9: "Restaurant",
    places__h3_10: "Hotel",
    places__h3_11: "Beauty Salon",
    places__h3_12: "Clinic",
    faq__span: "FAQ: Partnering with Us",
    faq__h2: "Common Questions About Collaboration",
    faq__h3_1: "How can my business benefit from hosting a charging station?",
    faq__answer_1:
      "Hosting a charging station can attract more customers, increase their time spent at your location, and enhance their overall experience. It also demonstrates your commitment to customer convenience and modern technology",
    faq__h3_2: "What does it cost to install a charging station?",
    faq__answer_2:
      "The installation of a charging station is usually free. You only need to provide space and electricity, while we take care of the rest.",
    faq__h3_3: "What kind of support do you offer to business partners?",
    faq__answer_3:
      "We provide full technical support, marketing materials, and regular maintenance to ensure smooth operation. Our team is always available to assist you with any questions or issues.",
    faq__h3_4: "How much space does the charging station require?",
    faq__answer_4:
      "The charging station requires minimal space, typically no more than a small shelf or counter area. It can be easily integrated into your existing setup without disrupting your business.",
    faq__h3_5:
      "What types of businesses are ideal for hosting a charging station?",
    faq__answer_5:
      "Charging stations are ideal for cafes, restaurants, shopping malls, hotels, airports, and any high-traffic locations where customers spend time and may need to charge their devices.",
    faq__h3_6: "How do I get started with a partnership?",
    faq__answer_6:
      "Getting started is easy! Simply contact us, and we’ll discuss the details, set up the charging station at your location, and provide ongoing support to ensure everything runs smoothly.",
    become_a_partner: "Become a partner",
    find_the_nearest_station: "Find the nearest station",
    pricing_policy: "Pricing policy",
    faq: "FAQ",
    all_rights_reserved: "All rights reserved",
    policy: "Policy",
    terms_of_use: "Terms of use",
  },
  pl: {
    "for-business": "Dla biznesu",
    "download-app": "Pobierz aplikację",
    h1: "Bądź w kontakcie, gdziekolwiek jesteś",
    p1: "Niezawodne ładowanie w każdej chwili!",
    "find-my-powerbank": "Znajdź Mój Power Bank",
    "phase-1": "na stacji autobusowej",
    "phase-2": "w sklepie",
    "phase-3": "w SPA",
    "phase-4": "w centrum handlowym",
    "phase-5": "na lotnisku",
    "phase-6": "na plaży",
    "phase-7": "w parku",
    "phase-8": "w biurze",
    "phase-9": "w kawiarni",
    "phase-10": "w pociągu",
    "phase-11": "w bibliotece",
    "phase-12": "na siłowni",
    "phase-13": "w kinie",
    "phase-14": "w restauracji",
    "phase-15": "w muzeum",
    "phase-16": "w sali koncertowej",
    "phase-17": "na szczycie góry",
    "phase-18": "na festiwalu",
    "phase-19": "w hotelu",
    "phase-20": "na łodzi",
    "get-the-app__span": "Pobierz aplikację",
    "get-the-app__h2": "Pobierz aplikację i nigdy nie zostawaj bez baterii",
    "get-the-app__p2":
      "Pobierz aplikację już teraz, aby łatwo znaleźć najbliższy power bank i naładować swoje urządzenia, gdziekolwiek jesteś!",
    "how-it-works": "Jak to działa",
    hiw__h3_1: "Pobierz aplikację",
    hiw__p2_1: "Zainstaluj naszą aplikację na swoim urządzeniu",
    hiw__h3_2: "Znajdź i zeskanuj",
    hiw__p2_1:
      "Użyj mapy w aplikacji, aby znaleźć najbliższy power bank i zeskanować kod QR",
    hiw__h3_3: "Wypożycz power bank",
    hiw__p2_3:
      "Wybierz power bank, którego potrzebujesz, i wypożycz go przez aplikację",
    hiw__h3_4: "Używaj i zwróć",
    hiw__p2_4:
      "Korzystaj z power banku i zwróć go do najbliższej stacji po zakończeniu użytkowania",
    hiw__span: "Niedrogie plany wynajmu",
    hiw__h2: "Proste ceny, żadnych ukrytych opłat",
    price__h3_1: "Pierwsza godzina",
    "price__price-itself_1": "Za darmo",
    price__subtext_1: "*Darmowe dla nowych użytkowników po rejestracji",
    price__h3_2: "Po 1 godzinie",
    "per-hour": "/opłata za godzinę",
    popular: "popularne",
    price__h3_3: "Cały dzień",
    "per-day": "/opłata za dzień",
    wmud__span: "Co nas wyróżnia",
    wmud__h3_1: "Dogodne lokalizacje",
    wmud__p2_1:
      "Znajdź power banki w stacjach wygodnie rozmieszczonych w całym mieście",
    wmud__h3_2: "Przyjazna aplikacja",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps. PLŁatwo znajdziesz, wypożyczysz i zwrócisz power banki w kilku kliknięciach",
    wmud__h3_3: "Wysokiej jakości urządzenia",
    wmud__p2_3:
      "Nasze power banki są niezawodne, szybko ładują i pasują do większości urządzeń",
    wmud__h3_4: "Przystępne ceny",
    wmud__p2_4: "Korzystaj z elastycznych planów wynajmu bez ukrytych opłat",
    map__span: "Mapa stacji",
    map__h2: "Znajdź najbliższą stację ładowania",
    map__p2:
      "Łatwo znajdź wszystkie pobliskie stacje power banków i miej energię zawsze pod ręką!",
    map__btn: "Znajdź stacje w pobliżu",
    "download-app__h2": "Doładowanie baterii w cenie butelki wody",
    "download-app__p2":
      "Szybkie, łatwe i przystępne – pobierz aplikację, aby być zawsze online",
    "slider__h3-1": "Bezpieczne płatności",
    "slider__p-1":
      "Dokonuj szybkich i bezpiecznych płatności bezpośrednio przez aplikację.",
    "slider__h3-2": "Przyjazny dla użytkownika interfejs",
    "slider__p-2":
      "Łatwe wynajmowanie, śledzenie i zwracanie power banków dzięki prostemu interfejsowi aplikacji",
    "slider__h3-3": "Śledzenie w czasie rzeczywistym",
    "slider__p-3":
      "Dokładnie wiesz, gdzie znaleźć stację dzięki naszej mapie na żywo.",
    "slider__h3-4": "Ekskluzywne oferty",
    "slider__p-4":
      "Ciesz się rabatami i korzyściami dostępnymi tylko dla użytkowników aplikacji",
    "slider__h3-5": "Zrównoważone rozwiązanie",
    "slider__p-5":
      "Wybierz ekologiczne, wielorazowe power banki i pomóż ograniczyć ilość odpadów",
    form__h2: "Chcesz nawiązać współpracę lub potrzebujesz wsparcia?",
    form__p2:
      "Masz pytania, sugestie lub chcesz zostać naszym partnerem? Wypełnij formularz, a my skontaktujemy się z Tobą wkrótce!",
    checkbox__p:
      "Przesyłając ten formularz wyrażasz zgodę na przetwarzanie swoich danych osobowych.",
    form__send: "wysłać",
    placeholder__name: "*your name",
    placeholder__email_or_phone: "*e-mail lub numer telefonu",
    placeholder__name: "*Twoje imię",
    placeholder__email_or_phone: "*e-mail lub numer telefonu",
    error__name_required: "Imię jest wymagane.",
    error__name_length: "Imię musi mieć od 2 do 20 znaków.",
    error__name_letters: "Imię może zawierać tylko litery.",
    error__email_phone_required: "E-mail lub numer telefonu jest wymagany.",
    error__phone_format:
      "Numer telefonu musi mieć od 10 do 15 cyfr, z lub bez znaku '+'.",
    error__email_format: "Proszę podać poprawny adres e-mail.",
    form__success_h2: "Dziękujemy za przesłanie!",
    form__success_p2:
      "Wkrótce skontaktujemy się z Tobą, aby omówić dalsze kroki. Nie mogę się doczekać współpracy z Tobą!",
    form__success_btn: "Ok",
    business__main_h1: "Współpracuj z nami, aby wzmocnić swój biznes",
    business__main_p1: "Zwiększ swój zasięg i utrzymuj kontakt z klientami",
    business__main_btn: "Rozpocznij",
    counts__h2: "Zarabiaj, oferując inteligentniejsze usługi",
    counts__h3_1: "700+",
    counts__p2_1: "firmy już z nami współpracują.",
    counts__h3_2: "99%",
    counts__p2_2: "wskaźnik zadowolenia klientów z naszych usług.",
    counts__h3_3: "24/7",
    counts__p2_3: "wsparcie w celu zapewnienia bezproblemowego działania.",
    counts__h3_4: "1M+",
    counts__p2_4: "urządzenia ładowane na całym świecie.",
    places__span: "Idealne lokalizacje biznesowe",
    places__h2: "Idealny dla firm o dużym natężeniu ruchu",
    places__p2:
      "Zapewnij wygodne rozwiązanie w zakresie opłat, które poprawi komfort Twoich klientów, generując jednocześnie dodatkowy dochód dla Twojej firmy.",
    places__h3_1: "Centrum handlowe",
    places__h3_2: "Sklep wielobranżowy",
    places__h3_3: "Lotnisko",
    places__h3_4: "Spa",
    places__h3_5: "Sala gimnastyczna",
    places__h3_6: "Przestrzeń coworkingowa",
    places__h3_7: "Miejsce wydarzenia",
    places__h3_8: "Biblioteka",
    places__h3_9: "Restauracja",
    places__h3_10: "Hotel",
    places__h3_11: "Salon piękności",
    places__h3_12: "Klinika",
    faq__span: "Często zadawane pytania: Współpraca z nami",
    faq__h2: "Często zadawane pytania dotyczące współpracy",
    faq__h3_1:
      "Jakie korzyści moja firma może zyskać dzięki udostępnieniu stacji ładowania?",
    faq__answer_1:
      "Posiadanie stacji ładowania może przyciągnąć więcej klientów, wydłużyć ich czas spędzony w Twoim lokalu i poprawić ich doświadczenie. To także pokazuje Twoje zaangażowanie w wygodę klientów i nowoczesne technologie.",
    faq__h3_2: "Ile kosztuje instalacja stacji ładującej?",
    faq__answer_2:
      "Instalacja stacji ładowania jest zazwyczaj bezpłatna. Wystarczy zapewnić miejsce i dostęp do prądu, a my zajmiemy się resztą.",
    faq__h3_3: "Jakie wsparcie oferujecie partnerom biznesowym?",
    faq__answer_3:
      "Oferujemy pełne wsparcie techniczne, materiały marketingowe oraz regularny serwis, aby zapewnić sprawne działanie stacji. Nasz zespół jest zawsze gotowy, aby pomóc w razie pytań lub problemów.",
    faq__h3_4: "Ile miejsca wymaga stacja ładująca?",
    faq__answer_4:
      "Stacja ładowania zajmuje minimalną przestrzeń, zazwyczaj nie więcej niż mała półka lub lada. Można ją łatwo wkomponować w istniejące wnętrze bez zakłócania działalności.",
    faq__h3_5: "Jakie rodzaje firm są idealne do hostowania stacji ładowania?",
    faq__answer_5:
      "Stacje ładowania świetnie sprawdzają się w kawiarniach, restauracjach, centrach handlowych, hotelach, na lotniskach oraz w innych miejscach o dużym natężeniu ruchu, gdzie klienci spędzają czas i mogą potrzebować naładować swoje urządzenia.",
    faq__h3_6: "Jak rozpocząć współpracę partnerską?",
    faq__answer_6:
      "Rozpoczęcie współpracy jest proste! Skontaktuj się z nami, omówimy szczegóły, zainstalujemy stację ładowania w Twojej lokalizacji i zapewnimy ciągłe wsparcie, aby wszystko działało bezproblemowo.",
    become_a_partner: "Zostań partnerem",
    find_the_nearest_station: "Znajdź najbliższą stację",
    pricing_policy: "Polityka cenowa",
    faq: "FAQ",
    all_rights_reserved: "Wszelkie prawa zastrzeżone",
    policy: "Polityka",
    terms_of_use: "Warunki użytkowania",
  },
};
